apiVersion: v1
kind: Deployment
metadata:
    name: products-app-deployment
    labels:
      app: products
spec:
    replicas: 3
    selector:
      matchLabels:
        app: products
    template:
      metadata:
        labels:
          app: products
      spec:
        containers:
        - name: products-container
          image: kumaranraj/sb-prod-app:v1
          ports:
          - containerPort: 8080

