apiVersion:
kind: Service
metadata:
  name: product-service
  labels:
    app: products
spec:
  selector:
    app: products
  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
  

